fix/change for postgresql db
tm-pe2/ad-api pull request #34
Opened 2022-05-05 09:43 UTC by GlennLz

2022-05-05 22:16 UTC, GlennLz commented
All tests are green, but some column names might have to be changed in the database on the VPN.
a bunch of names have been changed so you might want to check if your code that isn't included in the tests still works as intended...

add .env and .env.test in root, point .env.test to test database

DB_HOST=
DB_USER=
DB_PASSWORD=
DB_DATABASE=
DB_PORT=
JWTSECRET=

'npm run test' will truncate the tables, add dummy data en run the tests on the test database.

2022-05-05 23:16 UTC, PandaGamersHDNL commented
add the envs needed in the readme file

2022-05-14 14:48 UTC, DrunkenToast commented
Is this ready for review? This branch has a lot of changes. Try to keep branches shorter next time.

2022-05-15 11:11 UTC, DrunkenToast requested changes
I don't agree with many design choices that were made with the API but we obviously don't have the time to overhaul the API. I suggest to take a look at the comments.
Don't add any new features to this branch. We need to get this merged for the front-end.

2022-05-15 11:11 UTC, DrunkenToast commented on src/validations/customer-validation.ts
> +    if(!!await customerServices.getCustomerByUserId(id))
!! makes me anxious. Also you could just return the check.
Do a proper check here.

2022-05-15 11:11 UTC, DrunkenToast commented on src/validations/customer-validation.ts
> +}
Same comment as before. Applies to a lot of other places it seems.

2022-05-15 11:11 UTC, DrunkenToast commented on src/validations/employee-validation.ts
> +}
"I want to validate if a national security number is correct by checking if anyone else has this same national security number" How does that make any sense?
Use a library or regex for this.

If this is function, inside the validation folder, is to check if it already exists then rename the function to indicate as such.

This also isnt a promise, just a bool return type.

2022-05-15 11:11 UTC, DrunkenToast commented on src/validations/invoice-validation.ts
> +const checkCustomerExists = async ( id: number): Promise<boolean> => {
Like this. (So function names are inconsistent).
Just return the check, also not a promise. This applies to all other cases.

2022-05-15 11:11 UTC, DrunkenToast commented on tsconfig.json
>  {
erm?

2022-05-18 18:12 UTC, closed without merging