feat: Generate advance & annual invoices
tm-pe2/ad-api pull request #67
Opened 2022-06-15 21:08 UTC by GlennLz

2022-06-16 15:16 UTC, DriesOlbrechts requested changes

2022-06-16 15:21 UTC, DrunkenToast requested changes
Do you plan on making a route for this? /invoices/id/download and a route to "confirm payment" etc?

2022-06-16 15:21 UTC, DrunkenToast commented on src/queries/invoice.ts
> +`;
maybe also add a service function to modify the type.

2022-06-16 16:02 UTC, GlennLz commented on src/app.ts
> +    //await generateInvoices(INVOICE_TYPE.ADVANCE);
It's to run the algorithm without having to wait for the scheduler

2022-06-16 16:11 UTC, GlennLz commented on src/models/invoice.ts
> +    customer: Customer | null,
done

2022-06-17 20:27 UTC, DrunkenToast approved these changes

2022-06-17 22:06 UTC, DrunkenToast approved these changes

2022-06-17 22:06 UTC, Dries1234 approved these changes

2022-06-17 22:06 UTC, merged